//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr4d
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.DealEnd = new HashSet<DealEnd>();
        }
    
        public int deal_id { get; set; }
        public Nullable<int> realtor { get; set; }
        public Nullable<int> property_id { get; set; }
        public string type_of_deal { get; set; }
        public Nullable<System.DateTime> deal_date { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Realtor Realtor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealEnd> DealEnd { get; set; }
    }
}
